'use client';

import * as React from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { enable2FA } from '@/lib/api/security';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Loader2, QrCode, ShieldCheck, Download } from 'lucide-react';
import { toast } from 'sonner';

interface TwoFactorSetupProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function TwoFactorSetup({ open, onOpenChange }: TwoFactorSetupProps) {
  const queryClient = useQueryClient();
  const [step, setStep] = React.useState<1 | 2 | 3>(1);
  const [code, setCode] = React.useState('');
  const [backupCodes, setBackupCodes] = React.useState<string[]>([]);

  const enableMutation = useMutation({
    mutationFn: enable2FA,
    onSuccess: (codes) => {
      setBackupCodes(codes);
      setStep(3);
      queryClient.invalidateQueries({ queryKey: ['security-factors'] });
      queryClient.invalidateQueries({ queryKey: ['security-events'] });
      toast.success('Two-Factor Authentication enabled');
    }
  });

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6 || !/^\d+$/.test(code)) {
      toast.error('Please enter a valid 6-digit code');
      return;
    }
    enableMutation.mutate();
  };

  const resetAndClose = () => {
    setStep(1);
    setCode('');
    setBackupCodes([]);
    onOpenChange(false);
  };

  const downloadCodes = () => {
    const element = document.createElement("a");
    const file = new Blob([backupCodes.join('\n')], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "backup-codes.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <Dialog open={open} onOpenChange={(val) => {
      if (!val) resetAndClose();
      else onOpenChange(val);
    }}>
      <DialogContent className="sm:max-w-[425px]">
        {step === 1 && (
          <>
            <DialogHeader>
              <DialogTitle>Set up Two-Factor Authentication</DialogTitle>
              <DialogDescription>
                Scan the QR code below with your authenticator app (like Google Authenticator, Authy, or 1Password).
              </DialogDescription>
            </DialogHeader>
            <div className="flex flex-col items-center justify-center py-6">
              <div className="bg-white p-4 rounded-xl border">
                {/* Mock QR Code representation */}
                <QrCode className="h-40 w-40 text-black" />
              </div>
              <div className="mt-6 space-y-2 text-center w-full">
                <p className="text-sm font-medium">Or enter this key manually:</p>
                <code className="px-2 py-1 bg-muted rounded-md text-sm font-mono break-all text-center block">
                  JBSWY3DPEHPK3PXP
                </code>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={resetAndClose}>Cancel</Button>
              <Button onClick={() => setStep(2)}>Next</Button>
            </DialogFooter>
          </>
        )}

        {step === 2 && (
          <form onSubmit={handleVerify}>
            <DialogHeader>
              <DialogTitle>Verify Code</DialogTitle>
              <DialogDescription>
                Enter the 6-digit code generated by your authenticator app to verify setup.
              </DialogDescription>
            </DialogHeader>
            <div className="py-6 space-y-4">
              <Input
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                placeholder="000000"
                className="text-center text-2xl tracking-[0.5em] font-mono"
                maxLength={6}
                required
              />
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setStep(1)} disabled={enableMutation.isPending}>
                Back
              </Button>
              <Button type="submit" disabled={enableMutation.isPending || code.length !== 6}>
                {enableMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Verify & Enable
              </Button>
            </DialogFooter>
          </form>
        )}

        {step === 3 && (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-success" />
                2FA Enabled Successfully
              </DialogTitle>
              <DialogDescription>
                Save these backup codes in a secure place. They can be used to access your account if you lose your device. Each code can only be used once.
              </DialogDescription>
            </DialogHeader>
            <div className="py-4">
              <div className="grid grid-cols-2 gap-2 bg-muted p-4 rounded-md font-mono text-sm">
                {backupCodes.map((c, i) => (
                  <div key={i}>{c}</div>
                ))}
              </div>
              <Button variant="outline" className="w-full mt-4" onClick={downloadCodes}>
                <Download className="h-4 w-4 mr-2" /> Download Codes
              </Button>
            </div>
            <DialogFooter>
              <Button onClick={resetAndClose} className="w-full">Done</Button>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
